# Need this image line as mentioned on
# https://www.gitpod.io/docs/languages/deno/
image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      deno task start
